version: '3'

services:
  node:
    build: .
    ports:
      - '3000:3000'
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - node_net
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'practice'
    networks:
      - node_net

networks:
  node_net:
