version: '3'

services:
  node:
    build: .
    container_name: nodejs
    restart: always
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
